apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-byf6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-byf6@sha256:478b39c8dab86bb9531aa0eaafe2ddd899ca25f1c30e12c9b348f6b9783eea00
        name: my-nodejs
        resources: {}
status: {}
